- docs/resources/integration_oci_tenant.md
- internal/provider/gql.go
- internal/provider/integration_oci_tenant.go
This restructures the OCI integration to make the code more maintainable.
> 🧹 refactor oci integration

- internal/provider/gql.go
- internal/provider/policy_assignment_resource.go
> 🐛 fix preview and disbaled for policy assignment

- docs/resources/space.md
- internal/provider/custom_policy.go
- internal/provider/gql.go
- internal/provider/space_resource.go
- internal/provider/space_resource_test.go
fixes https://github.com/mondoohq/terraform-provider-mondoo/issues/32
> ⭐️  support custom space ids for space resource

- docs/resources/service_account.md
- examples/resources/mondoo_service_account/resource.tf
- go.mod
- internal/provider/service_account_resource.go
fixes https://github.com/mondoohq/terraform-provider-mondoo/issues/66
> ⭐️ output service account credential

- docs/resources/integration_gcp.md
- internal/provider/integration_gcp_resource.go
fixes https://github.com/mondoohq/terraform-provider-mondoo/issues/70
> 🧹 require gcp integration name

- docs/resources/integration_slack.md
- examples/resources/mondoo_integration_slack/resource.tf
- internal/provider/integration_slack_resource.go
- add markdown description
- use variable for slack token
- trigger scan with integration after the setup
> 🧹 improve the slack integration

- .copywrite.hcl
- LICENSE
> Update copyright date to 2024

- .github/actions/spelling/line_forbidden.patterns
- .github/actions/spelling/reject.txt
> Update the spellcheck pattern files

- internal/provider/integration_email_resource_test.go
- internal/provider/integration_gitlab_resource_test.go
> 🧹 fix acceptance tests

- docs/resources/integration_aws.md
- internal/provider/integration_aws_resource.go
- remove google reference
- clarify scanning behavior
> docs: update resource description

- internal/provider/gql.go
- internal/provider/integration_msdefender_resource.go
I accidentally introduced an error with the MsDefender import that affects every import and leads to an error.
This simple PR should fix it!
> 🐛 import error

- docs/resources/integration_github.md
- examples/resources/mondoo_integration_github/resource.tf
- internal/provider/integration_github_resource.go
Closes https://github.com/mondoohq/terraform-provider-mondoo/issues/184
> ✨ add missing discover settings to github resource

- internal/provider/space_resource.go
follow up to https://github.com/mondoohq/server/pull/10072/files
> 🧹 update space resource id requirements

- docs/index.md
- examples/provider/provider.tf
After https://github.com/mondoohq/terraform-provider-mondoo/pull/202
> Extend default provider example with configuration of policies and exceptions

- internal/provider/iam_workload_identity_binding.go
- internal/provider/iam_workload_identity_binding_test.go
> 🐛 fix WIF binding resource

- docs/resources/iam_workload_identity_binding.md
- internal/provider/iam_workload_identity_binding.go
- internal/provider/iam_workload_identity_binding_test.go
> 🐛 iam_workload_binding: replace space_id in favor of scope_mrn

- .github/actions/spelling/expect.txt
- .github/actions/spelling/line_forbidden.patterns
- .github/actions/spelling/patterns.txt
- .github/workflows/spell-check.yaml
- docs/resources/custom_policy.md
- docs/resources/custom_querypack.md
- internal/provider/custom_policy.go
- internal/provider/custom_querypack.go
- internal/provider/provider.go
- internal/provider/provider_test.go
- internal/provider/service_account_resource.go
Make sure we catch a few more things
> Expand the spellcheck for new terms

- internal/provider/integration_aws_serverless_resource.go
- internal/provider/integration_aws_serverless_resource_test.go
Make the VPCTagInput field in the VPCConfigurationStruct a pointer so it can be nil.
> 🧹 Make VPCTagInput field in the configuration a ptr

- internal/provider/custom_policy.go
- internal/provider/gql.go
> 🐛 custom_policy: set scope to platform by default

- GNUmakefile
just a small update to the makefile
> 🧹 add a note to make cmd to run tests about requirements (org SA)

- gen/gen.go
- gen/templates/gql_generated.go.tmpl
- gen/templates/integration_resource.go.tmpl
- internal/provider/gql.go
- internal/provider/gql_generated.go
- internal/provider/integration_azure_devops_resource.go
- internal/provider/integration_crowdstrike_resource.go
- internal/provider/integration_domain_resource.go
- internal/provider/integration_google_workspace_resource.go
- internal/provider/integration_msdefender_resource.go
- internal/provider/integration_okta_resource.go
and fixed CrowdstrikeFalcon and Sentinel import errors
> 🐛  Added read functionality for domain

- .github/workflows/test.yml
- .golangci.yml
- gen/gen.go
- internal/provider/policy_assignment_resource.go
- internal/provider/querypack_assignment_resource.go
Fixes https://github.com/mondoohq/terraform-provider-mondoo/pull/240
> 🧹 update .golangci.yml

- docs/resources/integration_jira.md
- internal/provider/integration_jira_resource.go
Updates to the Jira documentation to be more clear.
Closes: #276
> Update docs to be more clear for Jira drift tickets

- .github/workflows/cla.yaml
- .github/workflows/lint.yml
- .github/workflows/spell-check.yaml
- .github/workflows/test.yml
Related to: https://github.com/mondoohq/cnquery/pull/5947
> ✨ Pin GitHub actions to hashes
